# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lincoln/Documents/ECE/470/Kyber/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_3/fifo_generator_3.xci
# IP: The module: 'fifo_generator_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lincoln/Documents/ECE/470/Kyber/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.gen/sources_1/ip/fifo_generator_3/fifo_generator_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lincoln/Documents/ECE/470/Kyber/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.gen/sources_1/ip/fifo_generator_3/fifo_generator_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/lincoln/Documents/ECE/470/Kyber/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_3/fifo_generator_3.xci
# IP: The module: 'fifo_generator_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lincoln/Documents/ECE/470/Kyber/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.gen/sources_1/ip/fifo_generator_3/fifo_generator_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lincoln/Documents/ECE/470/Kyber/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.gen/sources_1/ip/fifo_generator_3/fifo_generator_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
