#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed May 20 05:16:34 +0000 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/data/home/lincoln/${SIM_VER_XSIM}/data"
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_15 -L mult_gen_v12_0_24 -L fifo_generator_v13_2_14 -L dist_mem_gen_v8_0_17 -L blk_mem_gen_v8_4_12 -L c_reg_fd_v12_0_11 -L c_shift_ram_v12_0_20 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_Kyber_top_protected_behav xil_defaultlib.tb_Kyber_top_protected xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_15 -L mult_gen_v12_0_24 -L fifo_generator_v13_2_14 -L dist_mem_gen_v8_0_17 -L blk_mem_gen_v8_4_12 -L c_reg_fd_v12_0_11 -L c_shift_ram_v12_0_20 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_Kyber_top_protected_behav xil_defaultlib.tb_Kyber_top_protected xil_defaultlib.glbl -log elaborate.log

