# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/claude_sandbox/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_5/fifo_generator_5.xci
# IP: The module: 'fifo_generator_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/claude_sandbox/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.gen/sources_1/ip/fifo_generator_5/fifo_generator_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /data/claude_sandbox/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.gen/sources_1/ip/fifo_generator_5/fifo_generator_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /data/claude_sandbox/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_5/fifo_generator_5.xci
# IP: The module: 'fifo_generator_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/claude_sandbox/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.gen/sources_1/ip/fifo_generator_5/fifo_generator_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /data/claude_sandbox/CRYSTALS-Kyber/Crystals-kyber/Crystals-kyber.gen/sources_1/ip/fifo_generator_5/fifo_generator_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
